### ISSUE TITLE
Compile error on Snow Leopard

### ISSUE THREAD

**Issue by thoni56** [reborg/pomodori#3]
I have a problem starting pomodori app that I downloaded as a binary release 0.5. I'm running MacOSX Mac OS X 10.6.2 (10C540), Darwin 10.2.0, Swedish. This is the output I get when I try it from the command line:

```
ThomasMacBook:cgreen thomas$ /Applications/Pomodori.app/Contents/MacOS/Pomodori 
/Applications/Pomodori.app/Contents/Frameworks/MacRuby.framework/Versions/0.5/usr/lib/ruby/1.9.0/time.rb:351: too short escaped multibyte character: /\A\s*
      (?:Mon|Tue|Wed|Thu|Fri|Sat|Sun),\x20
      (\d{2})\x20
      (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\x20
      (\d{4})\x20
      (\d{2}):(\d{2}):(\d{2})\x20
      GMT
      \s*\z/ix
/Applications/Pomodori.app/Contents/Frameworks/MacRuby.framework/Versions/0.5/usr/lib/ruby/1.9.0/time.rb:358: too short escaped multibyte character: /\A\s*
         (?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),\x20
         (\d\d)-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-(\d\d)\x20
         (\d\d):(\d\d):(\d\d)\x20
         GMT
         \s*\z/ix
/Applications/Pomodori.app/Contents/Frameworks/MacRuby.framework/Versions/0.5/usr/lib/ruby/1.9.0/time.rb:372: too short escaped multibyte character: /\A\s*
         (?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\x20
         (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\x20
         (\d\d|\x20\d)\x20
         (\d\d):(\d\d):(\d\d)\x20
         (\d{4})
         \s*\z/ix
timestamp.rb:1:in `<main>': compile error (SyntaxError)
from pomodori.rb:2:in `<main>'
```

**Comment by reborg** [comment]
Thanks Thomas for reporting. Looking into this.

**Comment by reborg** [comment]
Hi Thomas,

please open your "About This Mac" and copy paste here what you see after clicking on the "Hardware" section (default on open) and the "Software" section. I need to understand if you're running on a 32 bit machine (Core duo) or 64bit (Core 2 Duo).

Thanks

**Comment by thoni56** [comment]
32-bit!

Maskinvaruöversikt (= Hardware ;-) :

```
Modellnamn: MacBook
Modellidentifierare:    MacBook1,1
Processornamn:  Intel Core Duo
Processorhastighet: 2 GHz
Antal processorer:  1
Totalt antal kärnor:   2
L2-cache:   2 MB
Minne:  2 GB
Busshastighet:  667 MHz
Boot ROM-version:   MB11.0061.B03
SMC-version (system):   1.4f12
Serienummer (system):   4H62701LU9E
Maskinvaru-UUID:    00000000-0000-1000-8000-0016CBCEFADA
Rörelsedetektor (Sudden Motion Sensor):
Status: Aktiverad
```

Systemprogramöversikt:

```
Systemversion:  Mac OS X 10.6.2 (10C540)
Kärnversion:   Darwin 10.2.0
Startskiva: MacBook
Startläge: Normal
Datorns namn:   Thomas MacBook
Användarnamn:  Thomas Nilsson (thomas)
Säkert virtuellt minne:    Aktiverad
64-bitars kärna och tillägg:  Nej (=No!)
Tid sedan start:    6 dagar 1:34
```

**Comment by reborg** [comment]
Just skip this first paragraph about the technical details if you want. MacRuby which Pomodori uses underneath is not totally 32bit compatible. Something not working completely is for example the support for regular expressions that you just hit with this bug in time.rb httpdate method. I tried a few workaround to skip the httpdate time processing, but I can't even reproduce the problem on my 64bit machine and this alone makes almost impossible to produce a patch that works.

I know the MacRuby guys are working hard on fixing all the remaining 32 bit incompatibilities. It's pretty possible that by the time I'm able to produce a patch they already fixed this in MacRuby 0.6. So I'm asking you to wait until the problem is solved in MacRuby (probably March). Sorry for the trouble, I'll make it clear on the Pomodori website that if you have an "old" Core Duo Mac you have to wait until the next release of Pomodori. Thanks for your patience and support.

**Comment by thoni56** [comment]
That's too bad. But I'll wait ;-)

**Comment by thoni56** [comment]
Just tried this again. Downloaded Pomodori 0.6 from the website, still the same problem. Pomodori.app/Content/Frameworks/MacRuby.framework/Versions contains "0.5" and "Current", if that helps. (Still on 32bits, sorry. My MacBook never dies so I can get a new one... ;-)

I've also upgraded my MacRuby to 0.8 but that does not help either. How can I make sure that I'm using the latest MacRuby?
